// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkXJjAWMlv3C163Oqp5eQ3ItGfpwsqz1A',
    appId: '1:928475382565:web:bc9b0537e0e12c9102d0cc',
    messagingSenderId: '928475382565',
    projectId: 'whats-app-aec2e',
    authDomain: 'whats-app-aec2e.firebaseapp.com',
    storageBucket: 'whats-app-aec2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8h-KW6mpEu-kZVzdvJcHPD3B9-Hh7h28',
    appId: '1:928475382565:android:a49e5889da684dca02d0cc',
    messagingSenderId: '928475382565',
    projectId: 'whats-app-aec2e',
    storageBucket: 'whats-app-aec2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIMHwGcrJCjBxFOpxVx3M9dhdvBewuUx4',
    appId: '1:928475382565:ios:918839f99ae0dcb802d0cc',
    messagingSenderId: '928475382565',
    projectId: 'whats-app-aec2e',
    storageBucket: 'whats-app-aec2e.appspot.com',
    iosClientId: '928475382565-2e4e8nv7e1r1oumbufd41kncpci1iuov.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIMHwGcrJCjBxFOpxVx3M9dhdvBewuUx4',
    appId: '1:928475382565:ios:918839f99ae0dcb802d0cc',
    messagingSenderId: '928475382565',
    projectId: 'whats-app-aec2e',
    storageBucket: 'whats-app-aec2e.appspot.com',
    iosClientId: '928475382565-2e4e8nv7e1r1oumbufd41kncpci1iuov.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );
}
